import fs from 'node:fs'
import path from 'node:path'
import { create, getByID, load, search as oramaSearch } from '@orama/orama'
import { createTokenizer as createJapaneseTokenizer } from '@orama/tokenizers/japanese'
import { createTokenizer as createMandarinTokenizer } from '@orama/tokenizers/mandarin'
import { createContentHighlighter } from 'fumadocs-core/search'
import { i18nConfig } from '@/i18n'

// Load the pre-built Orama index generated by /api/build-search-index at build
// time and run searches against it. This keeps request times fast and avoids
// Vercel serverless function timeouts.
const advancedSchema = {
  content: 'string',
  page_id: 'string',
  type: 'string',
  tags: 'enum[]',
  url: 'string',
} as const

type AdvancedDocument = {
  content: string
  page_id: string
  type: string
  tags: string[]
  url: string
}

type ExportedIndex = {
  type: 'advanced'
  internalDocumentIDStore: { internalIdToId: string[] }
  index: unknown
  docs: unknown
  sorting: unknown
  language: string
}

let dbs: Map<string, { db: ReturnType<typeof create>; language: string }>

async function loadDBs() {
  if (dbs) return dbs

  dbs = new Map()
  const indexPath = path.resolve(
    process.cwd(),
    '.next/server/search-index.json'
  )

  if (!fs.existsSync(indexPath)) {
    const { searchAPI } = await import('@/lib/search-index')
    const exported = await searchAPI.export()
    fs.mkdirSync(path.dirname(indexPath), { recursive: true })
    fs.writeFileSync(indexPath, JSON.stringify(exported))
  }

  const data = JSON.parse(fs.readFileSync(indexPath, 'utf8')) as {
    type: 'i18n'
    data: Record<string, ExportedIndex>
  }

  for (const [locale, index] of Object.entries(data.data)) {
    const createParams: Parameters<typeof create>[0] = {
      schema: advancedSchema,
    }

    if (index.language === 'mandarin') {
      createParams.components = { tokenizer: createMandarinTokenizer() }
    } else if (index.language === 'japanese') {
      createParams.components = { tokenizer: createJapaneseTokenizer() }
    } else {
      createParams.language = index.language
    }

    const db = create(createParams)
    load(db, index as unknown as Parameters<typeof load>[1])
    dbs.set(locale, { db, language: index.language })
  }

  return dbs
}

async function searchAdvanced(
  db: ReturnType<typeof create>,
  query: string,
  tag: string[] = [],
  language: string
) {
  const baseParams = {
    groupBy: {
      properties: ['page_id'] as const,
      maxResult: 8,
    },
  }

  const searchParams =
    query.length > 0
      ? {
          ...baseParams,
          term: query,
          properties: ['content'] as const,
        }
      : baseParams

  const whereParams =
    tag.length > 0
      ? {
          ...searchParams,
          where: { tags: { containsAll: tag } },
        }
      : searchParams

  const highlighter = createContentHighlighter(query)
  const searchOptions =
    language === 'mandarin' || language === 'japanese'
      ? { threshold: 0, tolerance: 0 }
      : {}
  const result = await oramaSearch(db, {
    ...searchOptions,
    ...whereParams,
  } as unknown as Parameters<typeof oramaSearch>[1])
  const list: {
    id: string
    type: string
    content: string
    contentWithHighlights: ReturnType<typeof highlighter.highlight>
    url: string
  }[] = []

  for (const item of result.groups ?? []) {
    const pageId = item.values[0] as string
    const page = getByID(db, pageId) as AdvancedDocument | undefined

    if (!page) continue

    list.push({
      id: pageId,
      type: 'page',
      content: page.content,
      contentWithHighlights: highlighter.highlight(page.content),
      url: page.url,
    })

    for (const hit of item.result) {
      const doc = hit.document as AdvancedDocument
      if (doc.type === 'page') continue
      list.push({
        id: doc.page_id,
        content: doc.content,
        contentWithHighlights: highlighter.highlight(doc.content),
        type: doc.type,
        url: doc.url,
      })
    }
  }

  return list
}

export const GET = async (request: Request) => {
  const url = new URL(request.url)
  const query = url.searchParams.get('query')
  if (!query) return Response.json([])

  const locale = url.searchParams.get('locale') ?? i18nConfig.defaultLanguage
  const tag = url.searchParams.get('tag')?.split(',') ?? []

  const map = await loadDBs()
  const handler = map.get(locale)
  if (!handler) return Response.json([])

  return Response.json(
    await searchAdvanced(handler.db, query, tag, handler.language)
  )
}
